#!/usr/bin/env ruby
#^syntax detection

forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apt'
mod 'puppetlabs/concat'
mod 'puppetlabs/mysql'
#mod 'puppetlabs/apache'
mod 'puppetlabs/firewall'
#mod 'example42/git', :git => 'https://github.com/example42/puppet-git.git'
#mod 'example2/php', :git => 'https://github.com/example42/puppet-php.git'
#mod 'example42/resolver', :git => 'https://github.com/example42/puppet-resolver.git'
#mod 'example42/postfix', :git => 'https://github.com/lbhurtado/puppet-postfix.git'
#mod 'example42/dovecot', :git => 'https://github.com/example42/puppet-dovecot.git'
#mod 'example42/exim', :git => 'https://github.com/example42/puppet-exim.git'
#mod 'netmanagers/bind', :git => 'https://github.com/netmanagers/puppet-bind.git'
mod 'camptocamp/openssl', :git => 'https://github.com/camptocamp/puppet-openssl.git'
#mod 'smstools', :git => 'https://github.com/lbhurtado/puppet-smstools.git'
mod 'txtcmdr', :git => 'https://github.com/lbhurtado/puppet-txtcmdr.git'
#mod 'mailserver', :git => 'https://git.tetaneutral.net/puppet-mailserver.git'
