#!/usr/bin/env ruby
#^syntax detection

forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apt'
mod 'puppetlabs/concat'
mod 'puppetlabs/mysql'
mod 'puppetlabs/apache'
mod 'puppetlabs/firewall'
mod 'git', :git => 'https://github.com/example42/puppet-git.git'
mod 'php', :git => 'https://github.com/example42/puppet-php.git'
mod 'bind', :git => 'https://github.com/netmanagers/puppet-bind.git'
mod 'resolver', :git => 'https://github.com/example42/puppet-resolver.git'
mod 'postfix', :git => 'https://github.com/example42/puppet-postfix.git'
mod 'dovecot', :git => 'https://github.com/example42/puppet-dovecot.git'
